services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
    - ./Scripts/initDB.sql:/docker-entrypoint-initdb.d/0_init.sql
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
    ports:
      - 15672:15672
      - 5672:5672 
    expose:
      - '15672'
      - '5672'
  pulsar:
    image: apachepulsar/pulsar-all:4.0.0
    container_name: pulsar
    environment:
      PULSAR_STANDALONE_USE_ZOOKEEPER: 1
    ports:
      - 8080:8080
      - 6650:6650 
    expose:
      - '8080'
      - '6650'
    command: pulsar standalone
        